version: '3.8'

services:
  web:
    image: tasyamaslova/webapp-web:latest
    restart: always 
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:1@db/films2
      
  db:
    image: tasyamaslova/mysql2:latest 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: films2
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      
volumes:
  mysql-data:
